### ISSUE TITLE
repl keeps giving "Can only call functions and classes."

### ISSUE THREAD

**Issue by EraseKesu** [Jason2605/Dictu#217]
Hey, im testing out your programming language and when i try to call print(), it gives me "Can only call functions and classes." I am on linux manjaro.

**Comment by Jason2605** [comment]
Hi there! Thanks for the interest shown in the language and for submitting a potential bug report.

It would be great if i could get a little more information to be able to try and help you. A couple of things you could post are:
- A screenshot of the REPL
- The output of `print;` in the REPL (notice no parentheses)

**Comment by EraseKesu** [comment]
![image](https://user-images.githubusercontent.com/60030956/84068180-7d58ad80-a9c0-11ea-8984-e20b338a67f8.png)
here is an image of the output that i get when i type in `print("hello");` and `print;`

hope this helps

**Comment by Jason2605** [comment]
After a conversation it seems as though there was an issue during the compilation of the interpreter and a fresh clone and rebuild solved this issue.
