### ISSUE TITLE
Imports pollute global namespace

### ISSUE THREAD

**Issue by Jason2605** [Jason2605/Dictu#86]
someFile.du
```
def test() {
    print("Hello");
}
```

main.du
```
import "someFile.du";

test(); // Available via global namespace

someFile.test(); // We should prefer something like this
```

**Comment by kaidesu** [comment]
This would be better suited as an `include` statement for simple file includes, and then the `import` statement to import specific classes/functions from files :v:

**Comment by Jason2605** [comment]
There's a couple of routes we could go down with this, not quite decided yet. Your suggestion is one route, another is similar to Pythons where it's imported as a module. Another would be to introduce something like a namespace keyword. Unsure of the best option at this moment in time, however i do appreciate the input!
